#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
plugin_root="$repo_root/packages/plugin/tikz-funfig"

mkdir -p "$plugin_root/assets" "$plugin_root/skills" "$plugin_root/runtime/src" "$plugin_root/scripts"

python3 - "$repo_root" "$plugin_root" <<'PY'
from pathlib import Path
import json
import re
import shutil
import sys

repo = Path(sys.argv[1])
plugin = Path(sys.argv[2])

def refresh(source: Path, destination: Path) -> None:
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(
        source,
        destination,
        ignore=shutil.ignore_patterns(".DS_Store", "__pycache__", "*.pyc"),
    )

refresh(repo / "packages/skill", plugin / "skills/TIKZ-FunFig")
refresh(repo / "src/funfig", plugin / "runtime/src/funfig")
refresh(repo / "schemas", plugin / "runtime/schemas")
refresh(repo / "recipes", plugin / "runtime/recipes")
refresh(repo / "themes", plugin / "runtime/themes")
refresh(repo / "profiles", plugin / "runtime/profiles")
refresh(repo / "knowledge", plugin / "knowledge")
refresh(repo / "examples/templates", plugin / "runtime/templates")
refresh(repo / "examples", plugin / "runtime/gallery/examples")
(plugin / "runtime/gallery").mkdir(parents=True, exist_ok=True)
shutil.copy2(repo / "gallery/registry.json", plugin / "runtime/gallery/registry.json")

skills_manifest_path = repo / "packages/skills/index.json"
skills_manifest = json.loads(skills_manifest_path.read_text(encoding="utf-8"))
managed = {item["skill_id"] for item in skills_manifest.get("skills", [])}

# Remove only generated specialized Skill directories owned by this manifest.
skills_root = plugin / "skills"
for existing in list(skills_root.iterdir()):
    if existing.is_dir() and existing.name != "TIKZ-FunFig" and existing.name not in managed:
        marker = existing / ".funfig-generated-skill"
        if marker.is_file():
            shutil.rmtree(existing)

for item in skills_manifest.get("skills", []):
    skill_id = item["skill_id"]
    source = repo / item["source_dir"]
    if not (source / "SKILL.md").is_file():
        raise SystemExit(f"error: specialized Skill is missing SKILL.md: {source}")
    destination = skills_root / skill_id
    refresh(source, destination)
    (destination / ".funfig-generated-skill").write_text("generated by sync_plugin_package.sh\n", encoding="utf-8")
    scripts_dir = destination / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(repo / "packages/skill/scripts/funfig.sh", scripts_dir / "funfig.sh")

recipe_index = json.loads((repo / "recipes/index.json").read_text(encoding="utf-8"))
known_recipes = set(recipe_index.get("recipes", []))
card_index = json.loads((repo / "knowledge/cards/index.json").read_text(encoding="utf-8"))
known_cards = {item["id"] for item in card_index.get("cards", [])}
for item in skills_manifest.get("skills", []):
    missing_recipes = set(item.get("recipe_ids", [])) - known_recipes
    if missing_recipes:
        raise SystemExit(
            f"error: Skill {item['skill_id']} references unknown recipes: {sorted(missing_recipes)}"
        )
recipe_capabilities = {}
for recipe_id in known_recipes:
    recipe_path = repo / "recipes" / f"{recipe_id}.recipe.json"
    if not recipe_path.is_file():
        raise SystemExit(f"error: recipe registry entry has no file: {recipe_id}")
    recipe = json.loads(recipe_path.read_text(encoding="utf-8"))
    recipe_capabilities[recipe_id] = set(recipe.get("capabilities", []))
    missing_cards = set(recipe.get("knowledge_ids", [])) - known_cards
    if missing_cards:
        raise SystemExit(
            f"error: recipe {recipe_id} references unknown knowledge cards: {sorted(missing_cards)}"
        )
for item in skills_manifest.get("skills", []):
    available_capabilities = set()
    for recipe_id in item.get("recipe_ids", []):
        available_capabilities.update(recipe_capabilities.get(recipe_id, set()))
    missing_capabilities = set(item.get("capability_ids", [])) - available_capabilities
    if missing_capabilities:
        raise SystemExit(
            f"error: Skill {item['skill_id']} advertises capabilities not provided by its recipes: "
            f"{sorted(missing_capabilities)}"
        )

version_source = (repo / "pyproject.toml").read_text(encoding="utf-8")
match = re.search(r'(?m)^version\s*=\s*"([^"]+)"$', version_source)
if not match:
    raise SystemExit("error: could not resolve canonical pyproject.toml version")
runtime_source = (repo / "src/funfig/__init__.py").read_text(encoding="utf-8")
runtime_match = re.search(r'__version__\s*=\s*"([^"]+)"', runtime_source)
helper_source = (repo / "scripts/tff").read_text(encoding="utf-8")
helper_match = re.search(r'(?m)^VERSION\s*=\s*"([^"]+)"$', helper_source)
if not runtime_match or runtime_match.group(1) != match.group(1):
    raise SystemExit("error: runtime version drift; run 'python3 scripts/version.py sync'")
if not helper_match or helper_match.group(1) != match.group(1):
    raise SystemExit("error: tff helper version drift; run 'python3 scripts/version.py sync'")
manifest_path = plugin / "plugin.json"
manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
manifest["version"] = match.group(1)
manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
PY

cp "$repo_root/IconKitchen/macos/AppIcon128.png" "$plugin_root/assets/icon.png"
cp "$repo_root/IconKitchen/macos/AppIcon512.png" "$plugin_root/assets/logo.png"
cp "$repo_root/scripts/tff" "$plugin_root/scripts/tff"
chmod +x "$plugin_root/scripts/tff"

echo "ok: synchronized portable plugin -> $plugin_root"
